version: "4.0"

services:
  postgres:
    container_name: express_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      # - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    # volumes:
    #   - data:./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

    # volumes:
    #   - data:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  pg-admin:
    container_name: express_pg-admin_container
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_LISTEN_PORT=6060

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:6060"

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile.express
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://12345@postgres:5432/postgres
      - NODE_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_PORT=${POSTGRES_PORT}

  # product-service:
  #   build:
  #     context: ./product-service
  #     dockerfile: Dockerfile.product
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://product_db:5432/products

networks:
  default:
    driver: bridge

secrets:
  DATABASE_URL:
    external: true

# for postgresql
volumes:
  data:
  pgadmin-data:
