version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.user
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user_db:5432/users

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.product
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://product_db:5432/products

networks:
  default:
    driver: bridge
