version: "4.0"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.user
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user_db:5432/users

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.product
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://product_db:5432/products

networks:
  default:
    driver: bridge

secrets:
  DATABASE_URL:
    external: true
